export default {
  products: [
    {
      _id: "1",
      name: "Hoodie",
      category: "Hoodies",
      image: "/images/d2.jpg",
      price: 60,
      brand: "Vans",
      rating: 4.9,
      numReviews: 10,
      countInStock: 0,
    },
    {
      _id: "2",
      name: "Zip Hoodie",
      category: "Hoodies",
      image: "/images/d2.jpg",
      price: 70,
      brand: "Vans",
      rating: 4.6,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "Sweater",
      category: "Sweaters",
      image: "/images/d2.jpg",
      price: 40,
      brand: "Vans",
      rating: 4.5,
      numReviews: 10,
      countInStock: 4,
    },
    {
      _id: "4",
      name: "Sweater",
      category: "Sweaters",
      image: "/images/d2.jpg",
      price: 40,
      brand: "Vans",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: "5 ",
      name: "Sweater",
      category: "Sweaters",
      image: "/images/d2.jpg",
      price: 40,
      brand: "Vans",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
